# Generated by Django 5.2.11 on 2026-03-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPRAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metabolic_model', models.FileField(upload_to='gpr_models/')),
                ('genome_fasta', models.FileField(upload_to='gpr_genomes/')),
                ('results_file', models.FileField(blank=True, null=True, upload_to='gpr_results/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_count', models.IntegerField(blank=True, null=True)),
                ('matched_genes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpr_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPRBlastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=255)),
                ('complex_id', models.CharField(max_length=255)),
                ('evalue', models.FloatField()),
                ('bitscore', models.FloatField()),
                ('identity', models.FloatField()),
                ('query_coverage', models.FloatField()),
                ('gpr_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_results', to='GPR.gpranalysisjob')),
            ],
            options={
                'ordering': ['-bitscore'],
            },
        ),
    ]
