# Generated by Django 5.2.11 on 2026-03-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexMetadata',
            fields=[
                ('complex_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated list of aliases')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Complex Metadata',
            },
        ),
        migrations.AddField(
            model_name='gpranalysisjob',
            name='ambiguous_cases_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpranalysisjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ambiguity_review', 'Awaiting User Resolution'), ('completed', 'Completed'), ('error', 'Error')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='GPRAmbiguousCaseResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_gene', models.CharField(max_length=255)),
                ('reaction_id', models.CharField(max_length=255)),
                ('selected_complex', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gpr_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_resolutions', to='GPR.gpranalysisjob')),
            ],
            options={
                'ordering': ['genome_gene', 'reaction_id'],
                'unique_together': {('gpr_job', 'genome_gene', 'reaction_id')},
            },
        ),
    ]
