# Generated by Django 5.2.11 on 2026-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0002_complexmetadata_gpranalysisjob_ambiguous_cases_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpranalysisjob',
            name='message',
            field=models.TextField(blank=True, help_text='Current processing status message', null=True),
        ),
    ]
