# Generated by Django 5.2.11 on 2026-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0003_gpranalysisjob_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpranalysisjob',
            name='gpr_rules_json',
            field=models.TextField(blank=True, help_text='Mapping of reaction_id to GPR rule text', null=True),
        ),
        migrations.AddField(
            model_name='gpranalysisjob',
            name='updated_model_path',
            field=models.CharField(blank=True, help_text='Path to updated model with GPR rules', max_length=512, null=True),
        ),
    ]
