# Generated by Django 5.2.11 on 2026-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0004_gpranalysisjob_gpr_rules_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpranalysisjob',
            name='complex_summary_json',
            field=models.TextField(blank=True, help_text='Summary of gene-complex-reaction assignments for display', null=True),
        ),
    ]
