# Generated by Django 5.2.11 on 2026-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0005_gpranalysisjob_complex_summary_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpranalysisjob',
            name='has_unresolved_ambiguities',
            field=models.BooleanField(default=False, help_text='Indicates if ambiguous cases need user review (independent of job status)'),
        ),
    ]
