# Generated by Django 5.2.11 on 2026-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0006_gpranalysisjob_has_unresolved_ambiguities'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpranalysisjob',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
