# Generated by Django 5.2.11 on 2026-03-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPR', '0007_gpranalysisjob_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gprambiguouscaseresolution',
            unique_together=set(),
        ),
    ]
